[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '

[shell]
powershell_indicator = "ï‘ _"
zsh_indicator = "ğŸ"
bash_indicator = "ğŸ”¨"
disabled = false

[time]
disabled = false

