[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '

[shell]
powershell_indicator = "ï‘ _"
zsh_indicator = "ğŸ"
bash_indicator = "ğŸ”¨"
fish_indicator = "ğŸŸ"
disabled = false

[time]
disabled = false

[python]
python_binary = ["py"]
# The following isn't necessary, but convenient.
detect_folders = [".venv"]
